### ISSUE TITLE
Review Progress Tracking

### ISSUE THREAD

**Issue by alecloudenback** [alecloudenback/ModernFinancialModeling#180]
# Chapter Review Checklist

## Index and Front Matter
- [ ] Alec's initial review and revisions on index.qmd
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Why Program?
- [x] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Why Julia?
- [x] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Elements of Financial Modeling
- [x] Alec's initial review and revisions
- [x] #186
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Foundations of Programming
- [x] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### First Abstractions
- [x] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Type Abstractions
- [x] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Patterns Abstraction
- [x] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Hardware
- [x] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Performance (Single)
- [x] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Parallelization
- [x] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Software
- [x] Alec's initial review and revisions
- [x] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [x] Has an "In this chapter" section that is accurate

### Elements of Computer Science
- [x] Alec's initial review and revisions
- [x] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [x] Has an "In this chapter" section that is accurate

### Statistics
- [x] Alec's initial review and revisions
- [x] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [x] Has an "In this chapter" section that is accurate

### Automatic Differentiation
- [x] Alec's initial review and revisions
- [x] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [x] Has an "In this chapter" section that is accurate

### Optimization
- [x] Alec's initial review and revisions
- [x] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [x] Has an "In this chapter" section that is accurate

### Stochastic
- [x] Alec's initial review and revisions
- [x] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [x] Has an "In this chapter" section that is accurate

### Visualization
- [x] Alec's initial review and revisions
- [x] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Matrices
- [ ] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Data Learning
- [ ] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Julia Writing
- [ ] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Julia Debugging
- [ ] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Julia Sharing
- [ ] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Julia Optimizing
- [ ] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Stochastic Mortality
- [ ] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Scenario Generation
- [ ] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Similarity Calculation
- [ ] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Sensitivity Analysis
- [ ] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Portfolio Optimization
- [ ] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Bayesian Mortality
- [ ] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Other Techniques
- [ ] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### Ecosystem
- [ ] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate

### References
- [ ] Alec's initial review and revisions
- [ ] Chapter starts with a quote
- [ ] Checked that PDF formatting is good
- [ ] Has an "In this chapter" section that is accurate
